name: build_and_publish_container

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      # Restore cached Docker image layers
      - 
        name: Restore Docker Cache
        uses: actions/cache@v2
        with:
          path: /var/lib/docker
          key: docker-cache-{{ runner.os }}-${{ hashFiles('**/Dockerfile*') }}
          restore-keys: |
            docker-cache-{{ runner.os }}-
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/monitoring-station-backend:latest
      -
        name: Save Docker Cache
        uses: actions/cache@v2
        with: 
          path: /var/lib/docker
          key: docker-cache-{{ runner.os }}-${{ hashFiles('**/Dockerfile*') }}
